# Generated by Django 3.0.3 on 2020-02-19 15:30

from django.db import migrations, models
import menu.validators


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='images/%Y%m%d/', validators=[menu.validators.file_size], verbose_name='imagen'),
        ),
    ]
