# Generated by Django 3.0.3 on 2020-02-19 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambience', '0001_initial'),
        ('menu', '0002_auto_20200219_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='registrado a')),
                ('state', models.IntegerField(choices=[(1, 'Nuevo'), (2, 'Cancelado'), (3, 'Pagado')], verbose_name='estado')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_set', to='ambience.Table')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='registrado a')),
                ('attended_at', models.DateTimeField(blank=True, null=True, verbose_name='atendido a')),
                ('finalized_at', models.DateTimeField(blank=True, null=True, verbose_name='finalizado a')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detail_set', to='order.Invoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detail_set', to='menu.Item')),
            ],
        ),
    ]
