# Generated by Django 3.0.3 on 2020-02-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='entregado a'),
        ),
    ]
